### ISSUE TITLE
Publication Date - Custom field

### ISSUE THREAD

**Issue by jordanlewiz** [involved/posterity#3]
What are your thought about a 3rd date field `published-date`.

`created_at` and `last_modified` by default and then a `published_date` which is selected with some form of a date selector. This will allow for setting a post in the future or in the past and avoid issues when editing an old post and not changing its date.

**Comment by thetron** [comment]
This field already exists as `published_at` - which is part of the mongoid_publishable gem. This date field is not affected at all by updating a model - only by republishing.

Including additional form controls is entirely up to the developer, but I am personally against. Generally the only time you want to change the date on a post is when you've imported old posts, which you're updating. The `published_at` stamp is designed to reflect the date at which the post was published.

Occasionally, i've allowed for the published_at field to be accessible by only administrators in the form (i think gristmill has this feature) - but it usually feels a bit unnecessary.
